# NOTE: update this with your service name
service: lambdas

custom:
  bundle:
    ignorePackages:
      - pg-native

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: restaurants
    POSTGRES_HOST: localhost
    POSTGRES_PORT: 5432

functions:
  getRestaurant:
    handler: handlers/restaurant/getRestaurant.get
    events:
      - http:
          path: /restaurant/{id}
          method: get
          cors: true
  getAllRestaurants:
    handler: handlers/restaurant/getAllRestaurants.list
    events:
      - http:
          path: /restaurants
          method: get
          cors: true
